# Generated by Django 4.2.5 on 2023-11-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("number_of_students", models.IntegerField()),
                ("number_of_low_income_students", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "school_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KeystoneExam",
            fields=[
                (
                    "school_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("year", models.IntegerField()),
                ("percentage_bio_proficient", models.FloatField()),
                ("percentage_lit_proficient", models.FloatField()),
                ("percentage_alg_proficient", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PssaExam",
            fields=[
                ("percentage_eng_proficient", models.FloatField()),
                ("percentage_math_proficient", models.FloatField()),
                ("percentage_science_proficient", models.FloatField()),
                (
                    "school_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("aun", models.IntegerField()),
                ("school_name", models.CharField(max_length=255)),
                (
                    "school_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
