# Generated by Django 4.2.5 on 2023-11-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountyForm",
            fields=[
                ("county_id", models.IntegerField(primary_key=True, serialize=False)),
                ("county_name", models.CharField(max_length=255)),
            ],
        ),
    ]
