# Generated by Django 4.2.5 on 2023-11-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_countyform"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictForm",
            fields=[
                ("district_id", models.IntegerField(primary_key=True, serialize=False)),
                ("district_name", models.CharField(max_length=255)),
            ],
        ),
    ]
