# Generated by Django 4.2.5 on 2023-11-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_keystoneexam_school_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="districtform",
            name="county_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
