# Generated by Django 4.2.5 on 2023-12-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_districtform_county_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="keystoneexam", name="school_name",),
    ]
