# Generated by Django 4.2.5 on 2023-12-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_districtf_school_id_alter_school_school_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "school_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("high_school", models.IntegerField()),
                ("middle_school", models.IntegerField()),
                ("elementary_school", models.IntegerField()),
            ],
        ),
    ]
