# Generated by Django 4.2.5 on 2023-12-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_graph"),
    ]

    operations = [
        migrations.DeleteModel(name="Graph",),
    ]
