# Generated by Django 4.2.5 on 2023-12-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_delete_graph"),
    ]

    operations = [
        migrations.AddField(
            model_name="keystoneexam",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="keystoneexam",
            name="school_number",
            field=models.IntegerField(),
        ),
    ]
